development:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['APP_NAME'].to_s + '_dev' %>

test:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['APP_NAME'].to_s + '_test' %>