development:
  adapter: postgresql
  encoding: unicode
  database: punchbot_development
  pool: 5
  username: punchbot
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: punchbot_test
  pool: 5
  username: punchbot
  password: